const keyboardLegend = [
  { id: "-", label: "-", value: "-", size: "small", type: "char" },
  { id: ".", label: ".", value: ".", size: "small", type: "char" },
  { id: "'", label: "'", value: "'", size: "small", type: "char" },
  {
    id: "space",
    label: "space",
    value: " ",
    size: "space",
    type: "char",
  },
  { id: "a", label: "a", value: "a", size: "small", type: "char" },
  { id: "b", label: "b", value: "b", size: "small", type: "char" },
  { id: "c", label: "c", value: "c", size: "small", type: "char" },
  { id: "d", label: "d", value: "d", size: "small", type: "char" },
  { id: "e", label: "e", value: "e", size: "small", type: "char" },
  { id: "f", label: "f", value: "f", size: "small", type: "char" },
  { id: "g", label: "g", value: "g", size: "small", type: "char" },
  { id: "h", label: "h", value: "h", size: "small", type: "char" },
  { id: "i", label: "i", value: "i", size: "small", type: "char" },
  { id: "j", label: "j", value: "j", size: "small", type: "char" },
  { id: "k", label: "k", value: "k", size: "small", type: "char" },
  { id: "l", label: "l", value: "l", size: "small", type: "char" },
  { id: "m", label: "m", value: "m", size: "small", type: "char" },
  { id: "n", label: "n", value: "n", size: "small", type: "char" },
  { id: "o", label: "o", value: "o", size: "small", type: "char" },
  { id: "p", label: "p", value: "p", size: "small", type: "char" },
  { id: "q", label: "q", value: "q", size: "small", type: "char" },
  { id: "r", label: "r", value: "r", size: "small", type: "char" },
  { id: "s", label: "s", value: "s", size: "small", type: "char" },
  { id: "t", label: "t", value: "t", size: "small", type: "char" },
  { id: "u", label: "u", value: "u", size: "small", type: "char" },
  { id: "v", label: "v", value: "v", size: "small", type: "char" },
  { id: "w", label: "w", value: "w", size: "small", type: "char" },
  { id: "x", label: "x", value: "x", size: "small", type: "char" },
  { id: "y", label: "y", value: "y", size: "small", type: "char" },
  { id: "z", label: "z", value: "z", size: "small", type: "char" },
  { id: "enter", label: "enter", size: "large", type: "util" },
  { id: "shift", label: "shift", size: "medium", type: "util" },
  { id: "next", label: "next", size: "medium", type: "util" },
  { id: "prev", label: "prev", size: "medium", type: "util" },
  { id: "bksp", label: "bksp", size: "medium", type: "util" },
];

export default keyboardLegend;
