const keyboardLegend = {
  a: { label: "a", value: "a", size: "small" },
  b: { label: "b", value: "b", size: "small" },
  c: { label: "c", value: "c", size: "small" },
  d: { label: "d", value: "d", size: "small" },
  e: { label: "e", value: "e", size: "small" },
  f: { label: "f", value: "f", size: "small" },
  g: { label: "g", value: "g", size: "small" },
  h: { label: "h", value: "h", size: "small" },
  i: { label: "i", value: "i", size: "small" },
  j: { label: "j", value: "j", size: "small" },
  k: { label: "k", value: "k", size: "small" },
  l: { label: "l", value: "l", size: "small" },
  m: { label: "m", value: "m", size: "small" },
  n: { label: "n", value: "n", size: "small" },
  o: { label: "o", value: "o", size: "small" },
  p: { label: "p", value: "p", size: "small" },
  q: { label: "q", value: "q", size: "small" },
  r: { label: "r", value: "r", size: "small" },
  s: { label: "s", value: "s", size: "small" },
  t: { label: "t", value: "t", size: "small" },
  u: { label: "u", value: "u", size: "small" },
  v: { label: "v", value: "v", size: "small" },
  w: { label: "w", value: "w", size: "small" },
  x: { label: "x", value: "x", size: "small" },
  y: { label: "y", value: "y", size: "small" },
  z: { label: "z", value: "z", size: "small" },
  A: { label: "A", value: "A", size: "small" },
  B: { label: "B", value: "B", size: "small" },
  C: { label: "C", value: "C", size: "small" },
  D: { label: "D", value: "D", size: "small" },
  E: { label: "E", value: "E", size: "small" },
  F: { label: "F", value: "F", size: "small" },
  G: { label: "G", value: "G", size: "small" },
  H: { label: "H", value: "H", size: "small" },
  I: { label: "I", value: "I", size: "small" },
  J: { label: "J", value: "J", size: "small" },
  K: { label: "K", value: "K", size: "small" },
  L: { label: "L", value: "L", size: "small" },
  M: { label: "M", value: "M", size: "small" },
  N: { label: "N", value: "N", size: "small" },
  O: { label: "O", value: "O", size: "small" },
  P: { label: "P", value: "P", size: "small" },
  Q: { label: "Q", value: "Q", size: "small" },
  R: { label: "R", value: "R", size: "small" },
  S: { label: "S", value: "S", size: "small" },
  T: { label: "T", value: "T", size: "small" },
  U: { label: "U", value: "U", size: "small" },
  V: { label: "V", value: "V", size: "small" },
  W: { label: "W", value: "W", size: "small" },
  X: { label: "X", value: "X", size: "small" },
  Y: { label: "Y", value: "Y", size: "small" },
  Z: { label: "Z", value: "Z", size: "small" },
  "-": { label: "-", value: "-", size: "small" },
  ".": { label: ".", value: ".", size: "small" },
  "'": { label: "'", value: "'", size: "small" },
  space: { label: "space", value: " ", size: "space" },
  bksp: { label: "bksp", value: (input) => input.slice(0, -1), size: "medium" },
  enter: { label: "enter", size: "large" },
  shift: { label: "shift", size: "medium" },
  next: { label: "shift", size: "medium" },
};

const characterKeys = {
  "-": { label: "-", value: "-", size: "small" },
  ".": { label: ".", value: ".", size: "small" },
  "'": { label: "'", value: "'", size: "small" },
  a: { label: "a", value: "a", size: "small" },
  b: { label: "b", value: "b", size: "small" },
  c: { label: "c", value: "c", size: "small" },
  d: { label: "d", value: "d", size: "small" },
  e: { label: "e", value: "e", size: "small" },
  f: { label: "f", value: "f", size: "small" },
  g: { label: "g", value: "g", size: "small" },
  h: { label: "h", value: "h", size: "small" },
  i: { label: "i", value: "i", size: "small" },
  j: { label: "j", value: "j", size: "small" },
  k: { label: "k", value: "k", size: "small" },
  l: { label: "l", value: "l", size: "small" },
  m: { label: "m", value: "m", size: "small" },
  n: { label: "n", value: "n", size: "small" },
  o: { label: "o", value: "o", size: "small" },
  p: { label: "p", value: "p", size: "small" },
  q: { label: "q", value: "q", size: "small" },
  r: { label: "r", value: "r", size: "small" },
  s: { label: "s", value: "s", size: "small" },
  t: { label: "t", value: "t", size: "small" },
  u: { label: "u", value: "u", size: "small" },
  v: { label: "v", value: "v", size: "small" },
  w: { label: "w", value: "w", size: "small" },
  x: { label: "x", value: "x", size: "small" },
  y: { label: "y", value: "y", size: "small" },
  z: { label: "z", value: "z", size: "small" },
};

const utilityKeys = {
  enter: { label: "enter", size: "large" },
  shift: { label: "shift", size: "medium" },
  next: { label: "shift", size: "medium" },
};

export default keyboardLegend;
